# Generated by Django 3.1.7 on 2021-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_user',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
