# Generated by Django 3.1.7 on 2021-03-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20210316_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_user',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
