# Generated by Django 3.1.7 on 2021-03-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20210316_2315'),
        ('familylist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familylist.family')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Family_Item',
        ),
    ]
